QUESTIONS = [
    {"question": "Explain the difference between SQL and NoSQL databases and when you'd choose each.",
     "expected_concepts": ["schema vs schemaless", "ACID vs eventual consistency", "relational joins", "horizontal scaling for NoSQL"],
     "topic": "Databases"},
    {"question": "How does JWT authentication work?",
     "expected_concepts": ["header.payload.signature", "stateless", "signed not encrypted", "server verifies signature", "expiry claim"],
     "topic": "Authentication"},
    {"question": "What happens when you type a URL into a browser and press enter?",
     "expected_concepts": ["DNS lookup", "TCP handshake", "TLS", "HTTP request", "server response", "rendering"],
     "topic": "Networking"},
    {"question": "What's the difference between authentication and authorization?",
     "expected_concepts": ["who you are vs what you can do", "login vs permissions"],
     "topic": "Security"},
    {"question": "Explain database indexing and its trade-offs.",
     "expected_concepts": ["faster reads", "slower writes", "B-tree structure", "extra storage cost"],
     "topic": "Databases"},
    {"question": "What's the difference between HTTP GET and POST?",
     "expected_concepts": ["GET idempotent/cacheable/no body typically", "POST has body, used for creation/mutation", "safety and idempotency concepts"],
     "topic": "REST APIs"},
    {"question": "Explain what makes an API RESTful.",
     "expected_concepts": ["stateless", "resource-based URLs", "standard HTTP verbs", "representations (JSON/XML)"],
     "topic": "REST APIs"},
    {"question": "What are database transactions, and what does ACID stand for?",
     "expected_concepts": ["Atomicity", "Consistency", "Isolation", "Durability", "rollback on failure"],
     "topic": "Databases"},
    {"question": "Explain the difference between SQL INNER JOIN and LEFT JOIN.",
     "expected_concepts": ["INNER returns matching rows only", "LEFT returns all left rows plus matches, nulls otherwise"],
     "topic": "Databases"},
    {"question": "What is caching, and where would you apply it in a web application?",
     "expected_concepts": ["reduces repeated computation/DB calls", "browser cache, CDN, server-side cache (Redis)", "cache invalidation challenges"],
     "topic": "Caching"},
    {"question": "How would you design a basic rate limiter for an API?",
     "expected_concepts": ["token bucket / sliding window algorithms", "per-user/IP tracking", "429 response", "storage like Redis for counters"],
     "topic": "System Design"},
    {"question": "Explain horizontal vs vertical scaling.",
     "expected_concepts": ["horizontal = more machines", "vertical = bigger machine", "horizontal scaling trade-offs (complexity, load balancing)"],
     "topic": "Scaling"},
    {"question": "What is a load balancer, and why is it needed?",
     "expected_concepts": ["distributes traffic across servers", "improves availability/fault tolerance", "algorithms like round robin, least connections"],
     "topic": "Scaling"},
    {"question": "What's the difference between cookies and sessions?",
     "expected_concepts": ["cookies stored client-side", "sessions stored server-side, referenced by cookie/session ID", "security implications"],
     "topic": "Authentication"},
    {"question": "Explain the CAP theorem and how it applies to distributed systems.",
     "expected_concepts": ["Consistency, Availability, Partition tolerance", "can only guarantee 2 of 3 during a partition", "trade-off examples (CP vs AP systems)"],
     "topic": "Distributed Systems"},
    {"question": "What is API rate limiting used to prevent, and what happens when a client exceeds it?",
     "expected_concepts": ["abuse/DoS prevention, fair usage", "429 Too Many Requests response", "retry-after headers"],
     "topic": "REST APIs"},
]