QUESTIONS = [
    {"question": "Explain the difference between BFS and DFS. When would you use each?",
     "expected_concepts": ["queue vs stack", "level-order vs depth-first", "shortest path use case", "O(V+E)"],
     "topic": "Graphs"},
    {"question": "How would you detect a cycle in a linked list?",
     "expected_concepts": ["Floyd's cycle detection", "slow pointer", "fast pointer", "fast moves 2x", "meeting point", "O(n) time", "O(1) space"],
     "topic": "Linked Lists"},
    {"question": "How would you find the kth largest element in an array?",
     "expected_concepts": ["min-heap of size k", "quickselect", "O(n log k) or O(n) average"],
     "topic": "Arrays"},
    {"question": "Walk through your approach to the Two Sum problem.",
     "expected_concepts": ["hash map", "single pass", "O(n) time", "O(n) space"],
     "topic": "Hashing"},
    {"question": "Explain binary search and its time complexity.",
     "expected_concepts": ["sorted array requirement", "divide search space", "O(log n)", "mid pointer"],
     "topic": "Searching"},
    {"question": "What's the difference between a stack and a queue, and give a real use case for each.",
     "expected_concepts": ["LIFO vs FIFO", "call stack / undo use case", "task scheduling / BFS use case"],
     "topic": "Stacks & Queues"},
    {"question": "Explain how a hash table handles collisions.",
     "expected_concepts": ["chaining", "open addressing", "load factor", "rehashing"],
     "topic": "Hashing"},
    {"question": "Describe in-order, pre-order, and post-order tree traversal, and when each is useful.",
     "expected_concepts": ["left-root-right", "root-left-right", "left-right-root", "in-order gives sorted output for BST"],
     "topic": "Trees"},
    {"question": "What makes a Binary Search Tree efficient, and what breaks that efficiency?",
     "expected_concepts": ["O(log n) balanced", "degenerates to O(n) if unbalanced/skewed", "self-balancing trees like AVL/Red-Black"],
     "topic": "Trees"},
    {"question": "How would you represent a graph in code, and what are the trade-offs?",
     "expected_concepts": ["adjacency list", "adjacency matrix", "space O(V+E) vs O(V^2)", "dense vs sparse graphs"],
     "topic": "Graphs"},
    {"question": "Explain topological sorting and when it's needed.",
     "expected_concepts": ["DAG requirement", "dependency ordering", "DFS-based or Kahn's algorithm", "build systems / task scheduling"],
     "topic": "Graphs"},
    {"question": "What is the sliding window technique and when would you use it?",
     "expected_concepts": ["contiguous subarray/substring problems", "expand/shrink window pointers", "reduces O(n^2) to O(n)"],
     "topic": "Arrays"},
    {"question": "Explain the two-pointer technique with an example.",
     "expected_concepts": ["sorted array assumption often", "opposite ends or same direction pointers", "O(n) instead of O(n^2)"],
     "topic": "Arrays"},
    {"question": "How does merge sort work, and what's its time complexity?",
     "expected_concepts": ["divide and conquer", "recursive split", "merge step", "O(n log n)", "stable sort"],
     "topic": "Sorting"},
    {"question": "What is dynamic programming, and how do you recognize when to use it?",
     "expected_concepts": ["overlapping subproblems", "optimal substructure", "memoization vs tabulation", "example like Fibonacci or knapsack"],
     "topic": "Dynamic Programming"},
    {"question": "What's the time and space complexity of quicksort in average and worst case?",
     "expected_concepts": ["average O(n log n)", "worst O(n^2) on bad pivot", "in-place", "pivot selection strategies"],
     "topic": "Sorting"},
]